spring:
  cloud:
    gateway:
      routes:
        # 路由id
        - id: zero-client #主题导税服务
          # 路由的服务地址
          uri: lb://zero-client
          # 断言 Path: 配置路由映射路径
          predicates:
            - Path=/zero-client/**

#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#熔断配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #设置网关中路由转发请求的HystrixCommand执行超时时间
            timeoutInMilliseconds: 8000

# 打印网关日志信息
logging:
  level:
    org.springframework.cloud.gateway: debug
