server:
  port: 10001
  servlet:
    context-path: /zero-eureka

spring:
  application:
    name: zero-eureka

  #使用默认RibbonLoadBalancerClient
  cloud:
    loadbalancer:
      ribbon:
        enabled: false