eureka:
  instance:
    #配置与此实例相关联的主机名，是其他实例可以用来进行请求的准确名称
    hostname: ${spring.application.name}
    #显示服务ip地址
    prefer-ip-address: true
    #获取服务的ip和端口
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    #否从eureka服务器获取注册信息
    fetch-registry: false
    #是否注册到eureka-server
    register-with-eureka: false
  server:
    #服务注册中心的配置内容，指定服务注册中心的位置
    enable-self-preservation: false
