spring:
  #数据库配置
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 数据库连接
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seat-account?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

seata:
  application-id: fsp_tx_group
  tx-service-group: fsp_tx_group
  service:
    vgroup-mapping:
      fsp_tx_group: default