spring:
  #redis缓存
  redis:
    #数据库索引
    database: 0
    port: 6379
    #password:
    #连接超时时间
    timeout: 10000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 5
        max-active: 10
        max-wait: 1000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制)
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0

