spring:
  profiles:
    active: oracle
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none

logging:
  level:
    com.github.icezerocat: debug
    github:
      com:
        icezerocat:: debug